### 1) Регистрация схемы для топика "w7-topic" для значений
POST http://localhost:8081/subjects/w7-topic-value/versions
Content-Type: application/json

{
  "schema": "{ \"type\": \"record\", \"name\": \"Person\", \"namespace\": \"com.prosoft.domain\", \"fields\": [ { \"name\": \"id\", \"type\": \"long\" }, { \"name\": \"firstName\", \"type\": \"string\" }, { \"name\": \"lastName\", \"type\": \"string\" }, { \"name\": \"age\", \"type\": \"int\" } ] }"
}

### 2) Получить информацию о версии схемы #1 топика "w7-topic"
GET http://localhost:8081/subjects/w7-topic-value/versions/1
Accept: application/json

### 3) Изменить стратегию c "Backward Compatibility (Обратная совместимость)" (она по умолчанию) на стратегию "None (Без ограничений)"
PUT http://localhost:8081/config/w7-topic-value
Content-Type: application/json

{
  "compatibility": "NONE"
}

